#' @title Extract the Bayesian samples for a Gaussian mixture model generated by bd_do_inference
#'
#' @description
#' The input fit is the result of a call to stan by \code{bd_do_inference}, of
#' class stanfit. Return a matrix TH with dimensions S x (3*K), where S is the
#' number of samples (across all chains, and excluding warmup), and K is the
#' number of mixtures. The final column of as.matrix for class stanfit is the
#' log-posterior, which must be removed.
#'
#' @param fit The fit from stan, of class stanfit
#'
#' @return A matrix or list of samples
#' @export

bd_extract_param <- function(fit) {
  if (class(fit) != "stanfit") {
    stop(paste("Expected fit to be class stanfit, but it is", class(fit)))
  }
  # as.matrix is defined for class stanfit and excludes warmup samples
  TH <- as.matrix(fit)
  # Remove the final column, which is the log-posterior, not a parameter
  TH <- TH[, -ncol(TH)]

  return(TH)
}
