#' @title Add a shaded region showing the min/max quantiles
#'
#' @description Add a shaded region showing the min/max quantiles (usually +/-2.5%) to a plot
#'
#' @details The input, an, is the result of a call to analyze_soln. It is a
#' list-like object of class bayDem_analysis with information on the quantiles
#' of the density function and growth rate. Typically, the min/max quantiles
#' are 2.5% and 97.5%, but this can be changed via the input lev in the call to
#' analyze_soln.
#'
#' @param an A list-like object of class \code{baydem::bd_analysis} with information on the quantiles of the density function and growth rate
#' @param col The color of the shaded region
#' @param ... Additional parameters to pass to \code{graphics::polygon}
#'
#' @export
add_shaded_quantiles <-
  function(an,
           col = grDevices::adjustcolor("grey",
             alpha.f = 0.5
           ),
           ...) {

    # The indidces of the minimum and maximum quantiles
    indMin <- which.min(an$probs)
    indMax <- which.max(an$probs)
    graphics::polygon(c(an$tau, rev(an$tau)),
      c(
        an$Qdens[indMin, ],
        rev(an$Qdens[indMax, ])
      ),
      border = NA,
      xlab = NULL,
      col = col
    )
  }

#' @title Prepare a blank plot for showing densities
#'
#' @description Prepare a blank plot for showing densities
#'
#' @details The input, an, is the result of a call to analyze_soln. It is a
#' list-like object of class bayDem_analysis with information on the quantiles
#' of the density function and growth rate. Prepare a blank plot for adding
#' density information, e.g. by calling plot_50_percent_quantile and
#' add_shaded_quantiles.R. If the axis labels and limits are not specified,
#' sensible defaults are used.
#'
#' @param an A list-like object of class \code{baydem::bd_analysis} with
#' information on the quantiles of the density function and growth rate
#' @param xlim Numeric vector of length 2, giving the x coordinate range
#' @param ylim Numeric vector of length 2, giving the y coordinate range
#' @param xlab X axis label
#' @param ylab Y axis label
#' @param ... Additional parameters to pass to plot
#'
#' @export
make_blank_density_plot <-
  function(an,
           xlim = NA,
           ylim = NA,
           xlab = "Calendar Date [AD]",
           ylab = "Density",
           ...) {
    if (all(is.na(xlim))) {
      xlim <- range(an$tau)
    }

    if (all(is.na(ylim))) {
      # The following command works even if, e.g., f_sim is not in the list an
      # because an$f_sim results in NULL
      ylim <- c(0, max(c(max(an$Qdens), an$f_spdf, an$f_sim)))
    }

    graphics::plot(NULL,
      xlim = xlim,
      ylim = ylim,
      ylab = ylab,
      xlab = xlab,
      ...
    )
  }

#' @title Plot the 50 percent quantile curve
#'
#' @description Plot the 50% quantile curve
#'
#' @details The input, an, is the result of a call to analyze_soln. It is a
#' list-like object of class bayDem_analysis with information on the quantiles
#' of the density function and growth rate. By default, a new plot is made, but
#' if add = TRUE the curve is added to the active plot.
#'
#' @param an A list-like object of class \code{baydem::bd_analysis} with information on the quantiles of the density function and growth rate
#' @param add (default: `FALSE`) Whether to make a new plot or add to the active plot
#' @param ... Additional parameters to pass to plot / lines
#'
#' @export
plot_50_percent_quantile <- function(an, add = F, ...) {

  # The index of the 50 percent quantile
  ind50 <- which(an$probs == 0.5) # The index in probs / Qdens of the 50 percent quantile
  if (add) {
    graphics::lines(an$tau, an$Qdens[ind50, ], ...)
  } else {
    graphics::plot(an$tau, an$Qdens[ind50, ], type = "l", ...)
  }
}

#' @title Plot the known simulation density
#'
#' @description Plot the known simulation density
#'
#' @details The input, an, is the result of a call to analyze_soln. It is a
#' list-like object  with information on the quantiles of the density function
#' and growth rate. By default, a new plot is made, but if add = TRUE the curve
#'  is added to the active plot.
#'
#' @param an A list-like object generated by analyze_soln with information on the quantiles of the density function and growth rate
#' @param add (default: `FALSE`) Whether to make a new plot or add to the active plot
#' @param ... Additional parameters to pass to plot / lines
#'
#' @export
plot_known_sim_density <- function(an, add = F, ...) {
  if (add) {
    graphics::lines(an$tau, an$f_sim, ...)
  } else {
    graphics::plot(an$tau, an$f_sim, type = "l", ...)
  }
}

#' @title Plot the summed probability density function (SPDF)
#'
#' @description Plot the summed probability density function (SPDF)
#'
#' @details The input, an, is the result of a call to analyze_soln. It is a
#' list-like object of class bayDem_analysis with information on the quantiles
#' of the density function and growth rate. By default, a new plot is made, but
#' if add = TRUE the curve is added to the active plot.
#'
#' @param an A list-like object of class \code{baydem::bd_analysis} with information on the quantiles of the density function and growth rate
#' @param add (default: `FALSE`) Whether to make a new plot or add to the active plot
#' @param ... Additional parameters to pass to plot / lines
#'
#' @export
plot_summed_density <- function(an, add = F, ...) {
  if (add) {
    graphics::lines(an$tau, an$f_spdf, ...)
  } else {
    graphics::plot(an$tau, an$f_spdf, type = "l", ...)
  }
}

#' @title Visualize the calibration curve with equifinal and non-equifinal time spans
#'
#' @details
#' Vizualize the input calibration curve, calibDf, on the interval taumin to
#' taumax. This involves plotting the curve itself and shading invertible
#' (non-equifinal) and non-invertible (equifinal) regions.
#'
#' @param taumin The minimum calendar date for plotting (AD)
#' @param taumax The maximum calendar date for plotting (AD)
#' @param calibDf The calibration data frame, with columns yearBP, uncalYearBP, and uncalYearBPError
#' @param invertCol (default: `gray90`) The color for shading invertible regions
#' @param pointCol (default: `black`) The color for calibration curve points
#' @param pointPch (default: `19`) The symbol for calibration curve points
#' @param ... Additional inputs to plots
#'
#' @export
vis_calib_curve <-
  function(taumin,
           taumax,
           calibDf,
           invertCol = "gray90",
           pointCol = "black",
           pointPch = 19,
           ...) {
    tau_curve <- 1950 - calibDf$yearBP
    phi_curve <- exp(-calibDf$uncalYearBP / 8033)
    ind <- (tau_curve >= taumin) & (tau_curve <= taumax)
    tauVect <- tau_curve[ind]
    phiVect <- phi_curve[ind]
    phiMin <- min(phiVect)
    phiMax <- max(phiVect)

    # Create an empty plot
    graphics::plot(1, type = "n", xlim = c(taumin, taumax), ylim = c(phiMin, phiMax), ...)

    equiInfo <- assess_calib_curve_equif(calibDf)
    canInvert <- equiInfo$canInvert
    invSpanList <- equiInfo$invSpanList
    for (ii in 1:length(invSpanList)) {
      invSpan <- invSpanList[[ii]]
      if (dplyr::between(invSpan$tau_left, taumin, taumax) || dplyr::between(invSpan$tau_right, taumin, taumax)) {
        graphics::rect(invSpan$tau_left, phiMin, invSpan$tau_right, phiMax, border = NA, col = invertCol)
      }
    }

    # Draw calibration curve points
    graphics::points(tauVect, phiVect, col = pointCol, pch = pointPch)
  }
